# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TinderCardDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TinderCardDemo
  pod 'RIBs', '~> 0.9'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxCocoa'
  pod 'Alamofire', '~> 5.2'

  target 'TinderCardDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TinderCardDemoUITests' do
    # Pods for testing
  end

end
